spring:
  application:
    name: "@project.artifactId@"
    version: "@project.version@"
  jmx.enabled: true
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      database: ${MONGODB_DBNAME:idpay}
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      # custom configured properties
      config:
        connectionPool:
          maxSize: ${MONGODB_CONNECTIONPOOL_MAX_SIZE:100}
          minSize: ${MONGODB_CONNECTIONPOOL_MIN_SIZE:0}
          maxWaitTimeMS: ${MONGODB_CONNECTIONPOOL_MAX_WAIT_MS:120000}
          maxConnectionLifeTimeMS: ${MONGODB_CONNECTIONPOOL_MAX_CONNECTION_LIFE_MS:0}
          maxConnectionIdleTimeMS: ${MONGODB_CONNECTIONPOOL_MAX_CONNECTION_IDLE_MS:120000}
          maxConnecting: ${MONGODB_CONNECTIONPOOL_MAX_CONNECTING:2}

logging:
  level:
    org:
      springframework:
        cloud: ${LOG_LEVEL_SPRING_CLOUD:WARN}
        boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
        data: ${LOG_LEVEL_SPRING_DATA:INFO}
    root: ${LOG_LEVEL_ROOT:INFO}
    it:
      gov:
        pagopa: ${LOG_LEVEL_PAGOPA:INFO}

rest-client:
  reward:
    payment: ${IDPAY_REWARD_PAYMENT:idpay-reward-calculator}
    baseUrl: ${IDPAY_REWARD_PAYMENT:}

app:
  qrCode:
    throttlingSeconds: ${QR_CODE_PAYMENT_THROTTLING_SECONDS:${PAYMENT_THROTTLING_SECONDS:1}}
    trxInProgressLifetimeMinutes: ${QR_CODE_PAYMENT_TRX_TO_CONFIRM:${PAYMENT_TRX_TO_CONFIRM:15}}

management.endpoints:
  web:
    exposure.include: info, health

rest-client:
  reward:
    payment: ${IDPAY_REWARD_PAYMENT:idpay-reward-calculator}
    baseUrl: ${IDPAY_REWARD_PAYMENT:}

app:
  qrCode:
    throttlingSeconds: ${QR_CODE_PAYMENT_THROTTLING_SECONDS:${PAYMENT_THROTTLING_SECONDS:1}}
    throttlingMinutes: ${QR_CODE_PAYMENT_THROTTLING_MINUTES:${PAYMENT_THROTTLING_MINUTES:15}}